// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// optimal_vial_cost_single
List optimal_vial_cost_single(double dose_mg, NumericVector vial_sizes, NumericVector vial_costs, double wastage_threshold);
RcppExport SEXP _openqalyregimen_optimal_vial_cost_single(SEXP dose_mgSEXP, SEXP vial_sizesSEXP, SEXP vial_costsSEXP, SEXP wastage_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type dose_mg(dose_mgSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vial_sizes(vial_sizesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vial_costs(vial_costsSEXP);
    Rcpp::traits::input_parameter< double >::type wastage_threshold(wastage_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(optimal_vial_cost_single(dose_mg, vial_sizes, vial_costs, wastage_threshold));
    return rcpp_result_gen;
END_RCPP
}
// optimal_vial_cost_vec
NumericVector optimal_vial_cost_vec(NumericVector dose_mg_vec, NumericVector vial_sizes, NumericVector vial_costs, double wastage_threshold);
RcppExport SEXP _openqalyregimen_optimal_vial_cost_vec(SEXP dose_mg_vecSEXP, SEXP vial_sizesSEXP, SEXP vial_costsSEXP, SEXP wastage_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dose_mg_vec(dose_mg_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vial_sizes(vial_sizesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vial_costs(vial_costsSEXP);
    Rcpp::traits::input_parameter< double >::type wastage_threshold(wastage_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(optimal_vial_cost_vec(dose_mg_vec, vial_sizes, vial_costs, wastage_threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_openqalyregimen_optimal_vial_cost_single", (DL_FUNC) &_openqalyregimen_optimal_vial_cost_single, 4},
    {"_openqalyregimen_optimal_vial_cost_vec", (DL_FUNC) &_openqalyregimen_optimal_vial_cost_vec, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_openqalyregimen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
