# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimal_vial_cost_single <- function(dose_mg, vial_sizes, vial_costs, wastage_threshold = 0.0) {
    .Call(`_openqalyregimen_optimal_vial_cost_single`, dose_mg, vial_sizes, vial_costs, wastage_threshold)
}

optimal_vial_cost_vec <- function(dose_mg_vec, vial_sizes, vial_costs, wastage_threshold = 0.0) {
    .Call(`_openqalyregimen_optimal_vial_cost_vec`, dose_mg_vec, vial_sizes, vial_costs, wastage_threshold)
}

